name: base
channels:
    - conda-forge
dependencies:
    - python==3.10
    - dash
    - plotly
    - numpy
    - pandas
    - scipy
    - dash-bootstrap-components
    - geopy
    - pyproj
    - pip:
        - rasterio
        - rio-tiler
        - rich
        - dash_loading_spinners
